// packages/algo-params-vue/src/fc-create-algo.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { theme as antdTheme } from 'ant-design-vue';

// @ts-ignore
import FormCreate from '@form-create/ant-design-vue';

import type {
  FcCreateAlgoExpose,
  FcCreateAlgoProps,
  FcCreateAlgoPopupContainer,
  FormCreateSchema,
} from './types';

import {
  hasSerializedFunctionMarker,
  injectFormDataValues,
  injectInfoToRules,
  normalizePreviewRules,
} from './utils';

defineOptions({
  name: 'FcCreateAlgo',
});

const props = withDefaults(defineProps<FcCreateAlgoProps>(), {
  controlMaxWidth: '500px',
  emptyText: '暂无表单配置',
  infoFormatter: undefined,
  mode: 'preview',
  option: undefined,
  popupContainer: undefined,
  rule: () => [],
  showInfo: true,
});

const emit = defineEmits<{
  (event: 'change', formData: Record<string, any>): void;
  (event: 'ready', api: any): void;
  (event: 'submit', result: any): void;
  (event: 'validate', valid: boolean): void;
}>();

const formApi = ref<any>(null);
const formData = ref<Record<string, any>>({});
const schemaRule = ref<any[]>(props.rule ?? []);
const schemaOption = ref<Record<string, any> | undefined>(props.option);
const formKey = ref(0);
const { token } = antdTheme.useToken();

const defaultPopupContainer = (triggerNode: any) => {
  if (triggerNode?.parentNode) {
    return triggerNode.parentNode;
  }

  if (typeof document !== 'undefined') {
    return document.body;
  }

  return triggerNode;
};

const resolvePopupContainer = (
  popupContainer: FcCreateAlgoPopupContainer,
  triggerNode: any,
) => {
  if (typeof popupContainer === 'function') {
    return popupContainer(triggerNode) || defaultPopupContainer(triggerNode);
  }

  return popupContainer || defaultPopupContainer(triggerNode);
};

const resolveTooltipPopupContainer = (triggerNode: any) => {
  if (props.popupContainer) {
    return resolvePopupContainer(props.popupContainer, triggerNode);
  }

  if (typeof document !== 'undefined') {
    return document.body;
  }

  return defaultPopupContainer(triggerNode);
};

const injectInfoPopupContainer = (rules: any[]): any[] => {
  if (!Array.isArray(rules)) return [];

  return rules.map((item) => {
    if (typeof item !== 'object' || item === null) return item;

    const nextItem = { ...item };

    if (nextItem.info !== undefined && nextItem.info !== null && nextItem.info !== false) {
      const baseInfo =
        typeof nextItem.info === 'object'
          ? nextItem.info
          : { info: nextItem.info, show: true };

      nextItem.info = {
        ...baseInfo,
        getPopupContainer: (triggerNode: any) =>
          resolveTooltipPopupContainer(triggerNode),
      };
    }

    if (Array.isArray(nextItem.children) && nextItem.children.length > 0) {
      nextItem.children = injectInfoPopupContainer(nextItem.children);
    }

    return nextItem;
  });
};

const parseSchemaValue = <T,>(value: T): T => {
  if (!value || !FormCreate.parseJson || !hasSerializedFunctionMarker(value)) {
    return value;
  }

  return FormCreate.parseJson(JSON.stringify(value)) as T;
};

const processedRule = computed(() => {
  const rawRule = parseSchemaValue(
    Array.isArray(schemaRule.value) ? schemaRule.value : [],
  );
  const formDataMap = schemaOption.value?.formData || {};
  const ruleWithValues = injectFormDataValues(rawRule, formDataMap);
  const ruleWithInfo = props.showInfo
    ? injectInfoToRules(ruleWithValues, props.infoFormatter)
    : ruleWithValues;
  const ruleWithInfoPopup = props.showInfo
    ? injectInfoPopupContainer(ruleWithInfo)
    : ruleWithInfo;

  return props.mode === 'preview'
    ? normalizePreviewRules(ruleWithInfoPopup)
    : ruleWithInfoPopup;
});

const processedOption = computed(() => {
  const parsedOption = (parseSchemaValue(schemaOption.value) || {}) as Record<
    string,
    any
  >;
  const nextOption: Record<string, any> = {
    ...parsedOption,
    global: {
      ...parsedOption.global,
      '*': {
        ...parsedOption.global?.['*'],
        props: {
          ...parsedOption.global?.['*']?.props,
          getPopupContainer: (triggerNode: any) =>
            resolvePopupContainer(props.popupContainer, triggerNode),
        },
      },
    },
    resetBtn: parsedOption.resetBtn ?? false,
    submitBtn: parsedOption.submitBtn ?? false,
  };

  if (props.mode === 'preview' && nextOption.formData) {
    nextOption.formData = {};
  }

  return nextOption;
});

const containerStyle = computed(() => ({
  '--fc-create-card-hover-shadow-token':
    token.value.boxShadowSecondary || token.value.boxShadow,
  '--fc-create-control-max-width':
    typeof props.controlMaxWidth === 'number'
      ? `${props.controlMaxWidth}px`
      : props.controlMaxWidth,
  '--fc-create-empty-color-token':
    token.value.colorTextDescription || token.value.colorTextTertiary,
}));

watch(
  () => props.rule,
  (value) => {
    schemaRule.value = Array.isArray(value) ? value : [];
  },
  { deep: true },
);

watch(
  () => props.option,
  (value) => {
    schemaOption.value = value;
  },
  { deep: true },
);

watch(
  [
    schemaRule,
    schemaOption,
    () => props.mode,
    () => props.showInfo,
    () => props.infoFormatter,
    () => props.popupContainer,
    () => props.controlMaxWidth,
  ],
  () => {
    formKey.value += 1;
    formData.value = {};
  },
  { deep: true, immediate: true },
);

watch(
  formData,
  (value) => {
    emit('change', value);
  },
  { deep: true },
);

const handleMounted = (api: any) => {
  formApi.value = api;
  emit('ready', api);
};

const getApi: FcCreateAlgoExpose['getApi'] = () => formApi.value;

const getFormData: FcCreateAlgoExpose['getFormData'] = () => {
  if (!Array.isArray(schemaRule.value) || schemaRule.value.length === 0) {
    return null;
  }

  const currentFormData = formApi.value ? formApi.value.formData() : {};
  const latestOption = {
    ...(schemaOption.value || {}),
    formData: {
      ...(schemaOption.value?.formData || {}),
      ...currentFormData,
    },
  };

  return {
    rule: schemaRule.value,
    option: latestOption,
  } satisfies FormCreateSchema;
};

const setSchema: FcCreateAlgoExpose['setSchema'] = (rule = [], option) => {
  schemaRule.value = Array.isArray(rule) ? rule : [];
  schemaOption.value = option;
};

const reset: FcCreateAlgoExpose['reset'] = () => {
  formData.value = {};
  if (formApi.value) {
    formApi.value.resetFields();
  }
};

const validate: FcCreateAlgoExpose['validate'] = async () => {
  if (!formApi.value) {
    emit('validate', false);
    return false;
  }

  try {
    await formApi.value.validate();
    emit('validate', true);
    return true;
  } catch {
    emit('validate', false);
    return false;
  }
};

const submit: FcCreateAlgoExpose['submit'] = async () => {
  if (!formApi.value) return undefined;

  try {
    await formApi.value.submit();
    const result = formApi.value.submitResult;
    emit('submit', result);
    return result;
  } catch (error: any) {
    if (
      error?.outOfDate === true &&
      Array.isArray(error.errorFields) &&
      error.errorFields.length === 0
    ) {
      try {
        await formApi.value.submit(true);
        const result = formApi.value.submitResult;
        emit('submit', result);
        return result;
      } catch {
        return undefined;
      }
    }

    return undefined;
  }
};

defineExpose<FcCreateAlgoExpose>({
  getApi,
  getFormData,
  reset,
  setSchema,
  submit,
  validate,
});
</script>

<template>
  <div
    class="fc-create-algo"
    :class="{ 'is-edit-mode': mode === 'edit' }"
    :style="containerStyle"
  >
    <div class="fc-create-algo__scroll">
      <FormCreate
        v-if="processedRule.length > 0"
        :key="formKey"
        v-model="formData"
        v-model:api="formApi"
        :option="processedOption"
        :rule="processedRule"
        @mounted="handleMounted"
      />
      <div v-else class="fc-create-algo__empty">
        {{ emptyText }}
      </div>
    </div>
  </div>
</template>

// packages/algo-params-react/src/fc-create-algo-react.js
import React, {
  createElement as h,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';

import {
  Alert,
  Card,
  Cascader,
  Checkbox,
  Col,
  DatePicker,
  Divider,
  Form,
  Input,
  InputNumber,
  Radio,
  Row,
  Select,
  Slider,
  Space,
  Switch,
  TimePicker,
  Tooltip,
} from 'antd';

import {
  hasSerializedFunctionMarker,
  injectFormDataValues,
  injectInfoToRules,
  normalizePreviewRules,
  reviveSerializedFunctions,
} from './utils.js';

function getDefaultPopupContainer(triggerNode) {
  if (triggerNode?.parentNode) {
    return triggerNode.parentNode;
  }

  if (typeof document !== 'undefined') {
    return document.body;
  }

  return triggerNode;
}

function resolvePopupContainer(popupContainer, triggerNode) {
  if (typeof popupContainer === 'function') {
    return popupContainer(triggerNode) || getDefaultPopupContainer(triggerNode);
  }

  return popupContainer || getDefaultPopupContainer(triggerNode);
}

function parseSchemaValue(value) {
  if (!value || !hasSerializedFunctionMarker(value)) {
    return value;
  }

  return reviveSerializedFunctions(value);
}

function getFieldOptions(rule) {
  return rule.options || rule.props?.options || [];
}

function buildValidateRules(rule) {
  const rules = [];

  if (rule.$required) {
    rules.push({ required: true, message: rule.$required });
  }

  for (const item of rule.validate || []) {
    if (item?.pattern) {
      rules.push({
        pattern: new RegExp(item.pattern),
        message: item.message,
      });
      continue;
    }

    if (item?.type === 'email') {
      rules.push({ type: 'email', message: item.message });
      continue;
    }

    if (item?.type === 'url') {
      rules.push({ type: 'url', message: item.message });
      continue;
    }

    if (item?.minLen) {
      rules.push({ min: item.minLen, message: item.message });
    }
  }

  return rules;
}

function getLabel(rule) {
  return rule.title || rule.field || '';
}

function getInfoContent(rule, infoFormatter) {
  if (infoFormatter && (rule.field || (rule.type === 'div' && rule.title))) {
    return infoFormatter(rule);
  }

  if (typeof rule.info === 'string') {
    return rule.info;
  }

  if (rule.info?.content) {
    return rule.info.content;
  }

  if (rule.info?.info) {
    return rule.info.info;
  }

  if (rule.field) {
    return rule.field;
  }

  if (rule.type === 'div' && rule.title) {
    return rule.title;
  }

  return '';
}

function renderLabel(rule, infoFormatter) {
  const labelText = getLabel(rule);
  const infoContent = getInfoContent(rule, infoFormatter);

  if (!infoContent) {
    return labelText;
  }

  return h(
    'span',
    { className: 'fc-create-algo-react__label' },
    h('span', { className: 'fc-create-algo-react__label-text' }, labelText),
    h(
      Tooltip,
      {
        title: h(
          'span',
          { style: { whiteSpace: 'pre-line' } },
          String(infoContent),
        ),
        getPopupContainer: getDefaultPopupContainer,
      },
      h('span', { className: 'fc-create-algo-react__info' }, '?'),
    ),
  );
}

function renderDivContent(rule, key, renderRules) {
  if (Array.isArray(rule.children) && rule.children.length > 0) {
    if (typeof rule.children[0] === 'string') {
      return h(
        'div',
        { key, style: rule.style },
        rule.title ? h('div', null, rule.title) : null,
        rule.children.join(''),
      );
    }

    return h('div', { key, style: rule.style }, renderRules(rule.children));
  }

  return h('div', { key, style: rule.style }, rule.title || null);
}

function renderPreviewInput(rule, component, extraProps = {}) {
  return h(component, {
    ...rule.props,
    ...extraProps,
    value: rule.value,
    readOnly: true,
    bordered: false,
    allowClear: false,
  });
}

function renderFieldControl(rule, context) {
  const type = String(rule.type || '').toLowerCase();
  const commonPopupProps = {
    getPopupContainer: (triggerNode) =>
      resolvePopupContainer(context.popupContainer, triggerNode),
  };

  switch (type) {
    case 'input':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Input, { ...rule.props });

    case 'password':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input.Password)
        : h(Input.Password, { ...rule.props });

    case 'textarea':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input.TextArea)
        : h(Input.TextArea, { ...rule.props });

    case 'inputnumber':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(InputNumber, {
            ...rule.props,
            style: { width: '100%', ...rule.props?.style },
          });

    case 'select':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Select, {
            ...rule.props,
            ...commonPopupProps,
            options: getFieldOptions(rule),
          });

    case 'radio':
    case 'aradio':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(
            Radio.Group,
            { ...rule.props, options: getFieldOptions(rule) },
            null,
          );

    case 'checkbox':
    case 'acheckbox':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Checkbox.Group, {
            ...rule.props,
            options: getFieldOptions(rule),
          });

    case 'switch':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Switch, { ...rule.props });

    case 'slider':
    case 'aslider':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Slider, { ...rule.props });

    case 'cascader':
    case 'acascader':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Cascader, {
            ...rule.props,
            ...commonPopupProps,
            options: getFieldOptions(rule),
          });

    case 'datepicker':
    case 'adatepicker':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(DatePicker, {
            ...rule.props,
            ...commonPopupProps,
            style: { width: '100%', ...rule.props?.style },
          });

    case 'timepicker':
    case 'atimepicker':
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(TimePicker, {
            ...rule.props,
            ...commonPopupProps,
            style: { width: '100%', ...rule.props?.style },
          });

    default:
      return context.mode === 'preview'
        ? renderPreviewInput(rule, Input)
        : h(Input, { ...rule.props });
  }
}

function renderRule(rule, key, context, renderRules) {
  if (typeof rule === 'string') {
    return rule;
  }

  if (!rule || typeof rule !== 'object') {
    return null;
  }

  const type = String(rule.type || '').toLowerCase();

  if (type === 'acard') {
    return h(
      Card,
      {
        key,
        title: rule.props?.title || rule.title,
        size: rule.props?.size,
        bordered: rule.props?.bordered !== false,
        hoverable: rule.props?.hoverable,
        style: rule.style,
      },
      renderRules(rule.children || []),
    );
  }

  if (type === 'arow' || type === 'row') {
    return h(
      Row,
      { key, ...rule.props, style: rule.style },
      renderRules(rule.children || []),
    );
  }

  if (type === 'col') {
    return h(
      Col,
      { key, ...rule.props, style: rule.style },
      renderRules(rule.children || []),
    );
  }

  if (type === 'aspace' || type === 'space') {
    return h(
      Space,
      { key, ...rule.props, style: rule.style },
      renderRules(rule.children || []),
    );
  }

  if (type === 'adivider' || type === 'divider') {
    return h(
      Divider,
      { key, ...rule.props, style: rule.style },
      rule.title || rule.props?.title || null,
    );
  }

  if (type === 'aalert' || type === 'alert') {
    return h(Alert, {
      key,
      ...rule.props,
      message: rule.title || rule.props?.message,
      style: rule.style,
    });
  }

  if (type === 'div') {
    return renderDivContent(rule, key, renderRules);
  }

  if (!rule.field) {
    return null;
  }

  const itemProps = {
    key,
    name: rule.field,
    label: renderLabel(rule, context.infoFormatter),
    rules: buildValidateRules(rule),
    style: rule.style,
  };

  if (type === 'switch' && context.mode !== 'preview') {
    itemProps.valuePropName = 'checked';
  }

  return h(
    Form.Item,
    itemProps,
    renderFieldControl(rule, context),
  );
}

const FcCreateAlgoReact = forwardRef(function FcCreateAlgoReact(props, ref) {
  const {
    controlMaxWidth = '500px',
    emptyText = '暂无表单配置',
    infoFormatter,
    mode = 'preview',
    onChange,
    onReady,
    onSubmit,
    onValidate,
    option,
    popupContainer,
    rule = [],
    showInfo = true,
  } = props;

  const [form] = Form.useForm();
  const [schemaRule, setSchemaRule] = useState(Array.isArray(rule) ? rule : []);
  const [schemaOption, setSchemaOption] = useState(option);
  const apiRef = useRef({ submitResult: undefined });

  useEffect(() => {
    setSchemaRule(Array.isArray(rule) ? rule : []);
  }, [rule]);

  useEffect(() => {
    setSchemaOption(option);
  }, [option]);

  const parsedRule = useMemo(
    () => parseSchemaValue(Array.isArray(schemaRule) ? schemaRule : []),
    [schemaRule],
  );

  const parsedOption = useMemo(
    () => parseSchemaValue(schemaOption || {}),
    [schemaOption],
  );

  const processedRule = useMemo(() => {
    const formDataMap = parsedOption?.formData || {};
    const ruleWithValues = injectFormDataValues(parsedRule, formDataMap);
    const ruleWithInfo = showInfo
      ? injectInfoToRules(ruleWithValues, infoFormatter)
      : ruleWithValues;

    return mode === 'preview'
      ? normalizePreviewRules(ruleWithInfo)
      : ruleWithInfo;
  }, [infoFormatter, mode, parsedOption, parsedRule, showInfo]);

  const externalApi = useMemo(
    () => ({
      getFieldsValue: () => form.getFieldsValue(true),
      resetFields: () => form.resetFields(),
      setFieldsValue: (values) => form.setFieldsValue(values),
      submitResult: apiRef.current.submitResult,
      validateFields: () => form.validateFields(),
    }),
    [form],
  );

  useEffect(() => {
    apiRef.current.submitResult = undefined;
    form.resetFields();
    if (parsedOption?.formData) {
      form.setFieldsValue(parsedOption.formData);
    }
  }, [form, parsedOption, processedRule]);

  useEffect(() => {
    if (onReady) {
      onReady(externalApi);
    }
  }, [externalApi, onReady]);

  const handleValuesChange = (_, allValues) => {
    if (onChange) {
      onChange(allValues);
    }
  };

  const getFormData = () => {
    if (!Array.isArray(schemaRule) || schemaRule.length === 0) {
      return null;
    }

    const currentFormData = form.getFieldsValue(true);
    return {
      rule: schemaRule,
      option: {
        ...(schemaOption || {}),
        formData: {
          ...(schemaOption?.formData || {}),
          ...currentFormData,
        },
      },
    };
  };

  const submit = async () => {
    const values = await form.validateFields();
    const nextApi = {
      ...externalApi,
      submitResult: undefined,
    };

    if (typeof parsedOption?.onSubmit === 'function') {
      await parsedOption.onSubmit(values, nextApi);
    } else {
      nextApi.submitResult = values;
    }

    apiRef.current.submitResult = nextApi.submitResult;
    const result = nextApi.submitResult;

    if (onSubmit) {
      onSubmit(result);
    }

    return result;
  };

  const validate = async () => {
    try {
      await form.validateFields();
      if (onValidate) {
        onValidate(true);
      }
      return true;
    } catch {
      if (onValidate) {
        onValidate(false);
      }
      return false;
    }
  };

  const reset = () => {
    form.resetFields();
    if (parsedOption?.formData) {
      form.setFieldsValue(parsedOption.formData);
    }
  };

  const setSchema = (nextRule = [], nextOption) => {
    setSchemaRule(Array.isArray(nextRule) ? nextRule : []);
    setSchemaOption(nextOption);
  };

  useImperativeHandle(
    ref,
    () => ({
      getApi: () => ({
        ...externalApi,
        submitResult: apiRef.current.submitResult,
      }),
      getFormData,
      reset,
      setSchema,
      submit,
      validate,
    }),
    [externalApi, parsedOption, schemaOption, schemaRule],
  );

  const renderRules = (rules) =>
    (Array.isArray(rules) ? rules : []).map((item, index) =>
      renderRule(
        item,
        `${item?.field || item?.name || item?.type || 'node'}-${index}`,
        { infoFormatter, mode, popupContainer },
        renderRules,
      ),
    );

  const className = `fc-create-algo-react${mode === 'edit' ? ' is-edit-mode' : ''}`;

  return h(
    'div',
    {
      className,
      style: {
        '--fc-create-control-max-width':
          typeof controlMaxWidth === 'number'
            ? `${controlMaxWidth}px`
            : controlMaxWidth,
      },
    },
    h(
      'div',
      { className: 'fc-create-algo-react__scroll' },
      processedRule.length > 0
        ? h(
            Form,
            {
              form,
              layout: parsedOption?.form?.layout || 'horizontal',
              labelCol: parsedOption?.form?.labelCol,
              wrapperCol: parsedOption?.form?.wrapperCol,
              onValuesChange: handleValuesChange,
            },
            renderRules(processedRule),
          )
        : h('div', { className: 'fc-create-algo-react__empty' }, emptyText),
    ),
  );
});

export default FcCreateAlgoReact;
